// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"edustate/internal/biz"
	"edustate/internal/conf"
	"edustate/internal/data"
	"edustate/internal/server"
	"edustate/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, llm *conf.LLM, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	scoreRepo := data.NewScoreRepo(dataData)
	analysisUseCase := biz.NewAnalysisUseCase(scoreRepo, llm)
	analysisService := service.NewAnalysisService(analysisUseCase)
	tracerProvider := NewTraceProvider()
	grpcServer := server.NewGRPCServer(confServer, analysisService, tracerProvider, logger)
	httpServer := server.NewHTTPServer(confServer, analysisService, tracerProvider, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
